import re

def _casual_photo_transform(description: str) -> str:
    if not description:
        return description
    return re.sub(r'\brealistic\b', 'actual', description, flags=re.IGNORECASE)

ART_STYLES = [
    ("Painted Anime", "{description}, art in the style of atey ghailan, painterly anime style at pixiv, art in the style of kantoku, in art style of redjuice/nec\u00f6mi/rella/tiv pixiv collab, your name anime art style, masterpiece digital painting, exquisite lighting and composition, inspired by wlop art style, 8k, sharp, very detailed, high resolution, illustration. Overall, it's an absolute world-class masterpiece painterly anime-inspired digital art. It's an aesthetically pleasing painterly anime-inspired digital artwork with impeccable attention to detail and impressive composition. ^2 painterly anime artwork, {description}, world-class masterpiece, fine details, breathtaking artwork, painterly art style, high quality, 8k, very detailed, high resolution, exquisite composition and lighting. Overall, it's an absolute world-class masterpiece painterly anime artwork. It's an aesthetically pleasing painterly anime artwork with impeccable attention to detail and impressive composition.", None),
    ("Casual Photo", "A casual real-life photograph. A casual photo of {description}. It's a casual photo. Overall it's an actual real-life photograph.", _casual_photo_transform),
    ("Cinematic", "{description}, cinematic shot, dynamic lighting, 75mm, Technicolor, Panavision, cinemascope, sharp focus, fine details, 8k, HDR, realism, realistic, key visual, film still, cinematic color grading, depth of field. Overall, it's an absolute world-class cinematic masterpiece. It's an aesthetically pleasing cinematic shot with impeccable attention to detail and impressive composition.", None),
    ("Digital Painting", "{description}, breathtaking digital art, trending on artstation, in the style of atey ghailan, in the style of greg rutkowski, in the style of greg tocchini, in the style of james gilleard, 8k, high resolution, best quality. Overall, it's an absolute world-class masterpiece digital painting. It's an aesthetically pleasing digital painting with impeccable attention to detail and impressive composition.", None),
    ("Concept Art", "{description}, concept art, digital art, illustration, inspired by wlop style, 8k, fine details, sharp, very detailed, high resolution, world-class masterpiece. Overall, it's absolute world-class masterpiece concept art. It's an aesthetically pleasing concept art with impeccable attention to detail and impressive composition.", None),
    ("3D Disney Character", "3D cartoon Disney character portrait render. {description}, bokeh, 4k, highly detailed, Pixar render, CGI Animation, Disney, cute big circular reflective eyes, dof, cinematic film, Disney realism, subtle details, breathtaking Pixar short, fine details, close up, sharp focus, HDR, Disney-style octane render, incredible composition, superb lighting and detail, {description}. Overall, it's an absolute world-class masterpiece 3D Disney-inspired Character. It's an aesthetically pleasing 3D Disney-inspired piece with impeccable attention to detail and impressive composition.", None),
    ("2D Disney Character", "2D cartoon Disney character digital art of {description}. superb linework, classic 2D Disney style art, inspired in the style of the art styles of Glen Keane and Aaron Blaise, Disney-style character concept with a Disney-style face, trending on artstation, Disney-style version of {description}. Overall, it's an absolute world-class masterpiece 2D Disney-inspired Character. It's an aesthetically pleasing 2D Disney-inspired piece with impeccable attention to detail and impressive composition.", None),
    ("Disney Sketch", "Glen Keane character concept art black and white pencil sketch of {description}. rough pencil sketch in the style of Glen Keane, rough pencil sketch, close up, loose Disney-style character concept art sketch, nice sketchy pencil strokes, Disney character design sketch, pencil texture, a concept art pencil sketch of {description}, in the style of Glen Keane. Overall, it's an charmingly aesthetic and well-composed Disney-style sketch.", None),
    ("Concept Sketch", "black and white technical drawing showcasing a {description}, annotation details, world-class masterpiece black and white, pencil strokes, annotated technical concept art sketch, pencil texture. Overall, it's a charmingly aesthetic and well-composed concept sketch.", None),
    ("Painterly", "painterly digital painting, {description}, digital painting in the style of Ilya Kuvshinov with painterly brush strokes, in the style of Ilya Kuvshinov, world-class painterly masterpiece. Overall, it's an absolute world-class masterpiece painterly digital painting. It's an aesthetically pleasing painterly digital painting with impeccable attention to detail and impressive composition.", None),
    ("Oil Painting", "breathtaking alla prima oil painting, {description}, close up, alla prima style, oil on linen, painterly oil on canvas, painterly style, exquisite composition and lighting, modern painterly masterpiece, in the style of alexi zaitsev, award-winning painterly alla prima oil painting. Overall, it's an absolute world-class masterpiece oil painting. It's an aesthetically pleasing oil painting with impeccable attention to detail and impressive composition.", None),
    ("Oil Painting - Realism", "breathtaking oil painting, {description}, photorealistic oil painting, in the style of charlie bowater, fine details, in the style of wlop, trending on artstation, very detailed. Overall, it's an absolute world-class masterpiece realism oil painting. It's an aesthetically pleasing realism oil painting with impeccable attention to detail and impressive composition.", None),
    ("Oil Painting - Old", "{description}, Oil painting in the style of Jean-Fran\u00e7ois Millet and Gustave Courbet and Jules Breton", None),
    ("Oil Painting - 70s Pulp", "1970s vintage pulp art, ultra realistic, fully restored, exquisite lighting and composition, polished, masterpiece, vintage pulp art, in the style of Earle K. Bergey, in the style of Kelly Freas, in the style of Alex Schomburg, in the style of H. J. Ward, glossy pulp art, Amazing Stories, Weird Tales, 8k, high resolution, best quality, hyper-realistic, Mattias Adolfsson style, detailed stylization, {description}, ultra realistic, wlop-style, exquisite lighting and composition, polished, world-class masterpiece, digitally enhanced, breathtaking shot, subtle details, superb quality, art in the style of Kuvshinov, Kuvshinov style, detailed stylization. Overall, it's an absolute world-class masterpiece artwork. It's an aesthetically pleasing restored 1970s vintage pulp art with impeccable attention to detail and impressive composition. It has perfect contrast and color balance. Almost photorealism.", None),
    ("Professional Photo", "{description}, sharp focus, depth of field, 8k photo, HDR, professional lighting, taken with Canon EOS R5, DSLR, 75mm lens", None),
    ("Anime", "anime art of {description}, world-class masterpiece, 4k, best quality, anime art. Overall, it's an absolute world-class masterpiece anime-inspired artwork. It's an aesthetically pleasing anime art with impeccable attention to detail and beautiful composition.", None),
    ("Drawn Anime", "anime-style illustration with perfect clean lines, illustration of {description}, anime drawing/art, bold linework, illustration, cel shaded, anime-style digital illustration. It's an anime-inspired 2D-style anime illustration. Aesthetic high-skill, professional anime illustration, which looks like a screencap from an anime series. It has clean line work and a pleasant, appealing drawn aesthetic style. Overall, it's a world-class illustration with flawless line work, perfect composition, and impeccable attention to detail.", None),
    ("Anime Screencap", "Anime screencap, {description}. It's an anime screencap from a popular anime. Beautiful visual quality, remastered, extremely high quality, very aesthetic, high production value, high-skill masterpiece. The image shows impeccable and beautiful composition and contrast. It's an exquisite anime screencap style image.", None),
    ("Cute Anime", "adorable, cute, kawaii, {description}, cute moe anime character portrait, adorable, featured on pixiv, kawaii mo\u00e9 masterpiece, cuteness overload, very detailed, sooooo adorable. Overall, it's an absolute world-class masterpiece anime-inspired artwork. It's an aesthetically pleasing anime art with impeccable attention to detail and beautiful composition.", None),
    ("Soft Anime", "{description}, anime masterpiece with soft lighting, gentle intricate style, highly detailed, pixiv, anime art, 4k, art from your name anime, garden of words style art, high quality. Overall, it's an absolute world-class masterpiece soft beautiful anime-inspired artwork. It's an aesthetically pleasing, soft, beautiful anime art with impeccable attention to detail and beautiful composition.", None),
    ("Fantasy Painting", "{description}, d&d, fantasy, highly detailed, digital painting, artstation, sharp focus, fantasy art, illustration, 8k, in the style of greg rutkowski. It's an absolute world-class masterpiece artwork. It's an aesthetically pleasing artwork with impeccable attention to detail and impressive composition.", None),
    ("Fantasy Landscape", "{description}, fantasy matte painting, absolute masterpiece, detailed matte painting in the style of andreas rocha and greg rutkowski, in the style of Brothers Hildebrandt, superb composition, vivid fantasy art, breathtaking fantasy masterpiece. It's an absolute world-class masterpiece artwork. It's an aesthetically pleasing artwork with impeccable attention to detail and impressive composition.", None),
    ("Fantasy Portrait", "{description}, d&d, fantasy, highly detailed, digital painting, artstation, sharp focus, fantasy art, character art, illustration, 8k, art in the style of artgerm and greg rutkowski. It's an absolute world-class masterpiece artwork. It's an aesthetically pleasing artwork with impeccable attention to detail and impressive composition.", None),
    ("Studio Ghibli", "Studio Ghibli style artwork of {description}, Studio Ghibli style art film still, sharp, very detailed, high resolution, inspired by the style of Hayao Miyazaki, anime, film still from Spirited Away. In the style of Kiki Delivery Service, with a similar art style to Princess Mononoke. Aesthetically similar to My Neighbor Totoro's art style. Overall, it's an absolute world-class masterpiece Studio Ghibli-inspired artwork. It's an aesthetically pleasing classic Studio Ghibli style artwork with impeccable attention to detail and impressive composition.", None),
    ("50s Enamel Sign", "50s enamel sign of {description}, 50s advert enamel sign, masterpiece, authentic vintage enamel sign", None),
    ("Vintage Comic", "comic book style art of {description}, drawing, in the style of Dave Stevens, in the style of Adam Hughes, 1940's, 1950's, hand-drawn, color, high resolution, best quality, closeup", None),
    ("Franco-Belgian Comic", "franco-belgian color comic about {description}, bande dessin\u00e9e, franco-belgian comic panel, masterpiece, breathtaking composition, intricate, detailed, best quality", None),
    ("Tintin Comic", "color comic panel in the style of Herg\u00e9 about {description}, in the style of Herg\u00e9, tintin style, french comic panel, franco-belgian style, masterpiece, high-resolution Herg\u00e9 style", None),
    ("Medieval", "medieval illuminated manuscript picture of {description}, medieval illuminated manuscript art, masterpiece medieval color illustration, 16th century, 8k high-resolution scan of 16th century illuminated manuscript painting, detailed medieval masterpiece.", None),
    ("Pixel Art", "{description}, best pixel art, neo-geo graphical style, retro nostalgic masterpiece, 128px, 16-bit pixel art , 2D pixel art style, adventure game pixel art, inspired by the art style of hyper light drifter, masterful dithering, superb composition, beautiful palette, exquisite pixel detail", None),
    ("Furry - Oil", "{description}, crisp vibrant detailed soft painterly digital art, volumetric lighting, natural lighting, realistic lighting, vibrant colors, crisp oil painting, painterly realism, depth of field, subtle soft details, vivid, fresh, striking, in the style of chunie, in the style of darkgem, in the style of honovy, inspired by zaush, inspired by anhes, inspired by puinkey, in the style of caraid, in the style of dagasi, inspired by taranfiddler, in the style of atey ghailan, in the style of MilletGustave, in the style of Curbet, inspired by Charlie Bowater style, lol art. Overall, it's a world-class painterly masterpiece. It's aesthetically pleasing digitial art with impeccable attention to detail and impressive composition.", None),
    ("Furry - Cinematic", "{description}, cinematic shot, dynamic lighting, 75mm, Technicolor, Panavision, cinemascope, sharp focus, fine details, 8k, HDR, realism, realistic, key visual, film still, cinematic color grading, depth of field. Overall, it's an absolute world-class masterpiece. It's an aesthetically pleasing image with impeccable attention to detail and impressive composition.", None),
    ("Furry - Painted", "anthro {description} digital art, masterpiece, 4k, fine details. It's an absolute world-class masterpiece artwork. Overall, it's an aesthetically pleasing artwork with impeccable attention to detail and impressive composition.", None),
    ("Furry - Drawn", "anthro {description} illustration, hand-drawn, bold linework, anthro illustration, cel shaded, 4k, fine details, masterpiece. Overall, it's an absolute world-class masterpiece artwork. It's an aesthetically pleasing artwork with impeccable attention to detail and impressive composition.", None),
    ("Cute Figurine", "{description}, figurine, modern Disney style, octane render, chibi", None),
    ("3D Emoji", "masterpiece {description} cartoon 3D emoji concept render, close-up, facing forward, matte finish, 3D emoji render, app icon, simple design, new iOS 18.4 style {description} emoji render, simple background, centered, world-class masterpiece work of art, crisp render, sharp focus, charmingly aesthetic design, 4k, soft lighting, masterpiece emoji-style figurine 3D render, pure white background", None),
    ("Illustration", "breathtaking illustration of {description}, illustration, masterpiece, breathtaking illustration. Overall, it's an absolute world-class masterpiece illustration. It's an aesthetically pleasing illustration with impeccable attention to detail and impressive composition.", None),
    ("Cute Illustration", "A cute cartoon showing {description}, in a soft, cute, minimalist, webcomic-style illustration. Line art is somewhat bold but gentle, with clean lines, and subtle variation. Colors are soft, flat, with gentle pastel tones. No shading except for light inner shadows or simple highlights. The background is plain white or contains a light wash of color with subtle textured style. The overall scene is wholesome and endearing like a page from a Liz Climo comic. Composition is centered with space around the character, evoking authentic warmth through the wholesome, soft, web comic style. It's an aesthetically pleasing masterpiece, showing high skill in evoking an authentic and beautifully minimalist style.", None),
    ("Flat Illustration", "{description}, illustration, flat, 2D, vector art, masterpiece, made with adobe illustrator, behance competition winner, trending on dribble, 4k, high resolution, crisp lines. Overall, it's an absolute world-class masterpiece flat-style illustration. It's an aesthetically pleasing flat-style illustration with impeccable attention to detail and impressive composition.", None),
    ("Watercolor", "{description}, (watercolor), high resolution, intricate details, 4k, wallpaper, concept art, watercolor on textured paper. Overall, it's an absolute world-class masterpiece watercolor artwork. It's an aesthetically pleasing watercolor artwork with impeccable attention to detail and impressive composition.", None),
    ("1990s Photo", "{description}, 90s home video, nostalgic 90s photo, taken with kodak disposable camera", None),
    ("1980s Photo", "famous vintage 80s photo, {description}, grainy photograph, 80s photo with film grain, Kodacolor II 80s photo with vignetting, retro, r/OldSchoolCool, 80s photo with wear and tear and minor creasing and scratches, vintage color photo", None),
    ("1970s Photo", "famous vintage 70s photo, {description}, grainy photograph, 1970s photo with film grain, 70s photo with vignetting, retro, r/OldSchoolCool, 70s photo, vintage photo", None),
    ("1960s Photo", "famous vintage 60s photo, {description}, grainy photograph, 1960s photo with film grain, 60s photo with vignetting, retro, r/OldSchoolCool, 60s photo, vintage photo", None),
    ("1950s Photo", "famous vintage 50s photo, {description}, grainy photograph, 1950s photo with film grain, 1950s photo with vignetting, retro, r/OldSchoolCool, 1950s photo, vintage photo", None),
    ("1940s Photo", "famous vintage 1940s photo, {description}, grainy photograph, 1940s photo with film grain, 1940s photo with vignetting, retro, r/OldSchoolCool, 1940s photo, vintage photo", None),
    ("1930s Photo", "famous vintage 1930s photo, {description}, grainy photograph, 1930s photo with film grain, 1930s photo with vignetting, retro, r/OldSchoolCool, 1930s photo, vintage photo", None),
    ("1920s Photo", "famous vintage 1920s photo, {description}, 1920s photo, restored photograph, sepia, historical archive photo", None),
    ("Vintage Pulp Art", "1970s vintage pulp art, {description}, vintage pulp art, in the style of Earle K. Bergey, in the style of Kelly Freas, in the style of Alex Schomburg, in the style of H. J. Ward, glossy pulp art, Amazing Stories, Weird Tales, 8k, high resolution, best quality", None),
    ("50s Infomercial Anime", "{description}, 1950s infomercial style, delicate linework, paprika anime art style, chromatic aberration glow, 2d painted cel animation, soft focus, 2D pixiv 1950s", None),
    ("3D Pokemon", "An incredibly perfect high-quality 3D render of a pokemon creature, {description}, 8k render, beautiful pokemon digital art, fakemon, pokemon creature, cryptid, fakemon, masterpiece, soft focus, best quality, high quality. Perfect soft lighting, beautiful composition. It's an impressive CGI image from the upcoming Pokemon Movie (2026). Overall, it's an absolute world-class masterpiece 3D-rendered Pokemon-inspired creature. It's an aesthetically pleasing 3D Pokemon-inspired piece with impeccable attention to detail and impressive composition.", None),
    ("Painted Pokemon", "Beautiful, very high-quality painterly digital concept art, {description}, 8k digital painting of a pokemon, amazing pokemon creature art in the style of piperdraws, cryptid creations in the style of Piper Thibodeau, in the style of Naoki Saito and Tokiya, incredible composition. Overall, it's an absolute world-class masterpiece painterly Pokemon-inspired artwork. It's an aesthetically pleasing painterly Pokemon-inspired artwork with impeccable attention to detail and impressive composition.", None),
    ("2D Pokemon", "{description}, pokemon creature concept, superb line art, beautiful colors and composition, 2D art style, beautiful pokemon digital art, fakemon, in the style of Sowsow, pokemon creature, cryptid, fakemon, masterpiece, in the style of Yuu Nishida, 4k. The Pok\u00e9mon-like creature is centered within this anime-style 2D image. It's from the upcoming Pokemon Movie (2026) which has the classic 2D Pokemon art style. Overall, it's an absolute world-class masterpiece 2D Pokemon-inspired artwork. It's an aesthetically pleasing 2D Pokemon-inspired artwork with impeccable attention to detail and impressive composition. Clean, perfect linework, impeccable clean 2D anime-inspired art style.", None),
    ("Vintage Anime", "{description}, 1990s anime, vintage anime, 90's anime style, in the style of hajime sorayama, in the style of greg tocchini, anime masterpiece, pixiv, akira-style art, akira anime art, 4k, high quality. Overall, it's an absolute world-class masterpiece vintage anime artwork. It's an aesthetically pleasing vintage anime artwork with impeccable attention to detail and impressive composition.", None),
    ("Neon Vintage Anime", "{description}, neon vintage anime style, 90's anime style, 1990s anime, hajime sorayama, greg tocchini, neon vintage anime masterpiece, anime art, 4k, high quality. Overall, it's an absolute world-class masterpiece neon vintage anime artwork. It's an aesthetically pleasing neon vintage anime artwork with impeccable attention to detail and impressive composition.", None),
    ("Manga", "{description}, incredible hand-drawn manga, black and white, in the style of Takehiko Inoue, in the style of Katsuhiro Otomo and akira toriyama manga, hand-drawn art in the style of rumiko takahashi and Inio Asano, Ken Akamatsu manga art. Overall, it's an absolute world-class masterpiece black and white manga-style artwork. It's an aesthetically pleasing black and white manga artwork with impeccable attention to detail and impressive composition.", None),
    ("Fantasy World Map", "beautiful fantasy map of {description}, beautiful fantasy map inspired by middle earth and azeroth and discworld and westeros and essos and the witcher world and tamriel and faer\u00fbn and thedas, 4k, beautiful colors, crisp, high-resolution artistic map, topographic 3D terrain, artistic map. Overall, it's an absolute world-class masterpiece fantasy world map. It's an aesthetically pleasing fantasy world map artwork with impeccable attention to detail and impressive composition.", None),
    ("Fantasy City Map", "an aerial view of a city, TTRPG city map showing the full city, {description}, fantasy art, highly-skilled senior environment artist piece, beautiful fantasy map. Overall, it's an absolute world-class masterpiece fantasy city map. It's an aesthetically pleasing fantasy city map artwork with impeccable attention to detail and impressive composition.", None),
    ("Old World Map", "fantasy world map of {description}, fantasy world map, highly detailed digital painting, fantasy art, map illustration, 8k. Overall, it's an absolute world-class masterpiece old world map. It's an aesthetically pleasing old world style map artwork with impeccable attention to detail and impressive composition.", None),
    ("3D Isometric Icon", "{description}, 3D isometric render of cute {description}, 3D app icon, clean isometric design, beautiful design, soft gradient background, soft colors, centered, 3D blender render, masterpiece, best quality, high resolution, 8k octane render, beautiful color scheme, soft smooth lighting, physically based rendering, square image, high polycount", None),
    ("Flat Style Icon", "{description}, creative icon, flat style icon, masterpiece, high resolution, crisp, beautiful composition and color choice, beautiful flat painted style, behance contest-winner, award winning icon illustration, 8k, best quality", None),
    ("Flat Style Logo", "beautiful flat-style logo design depicting {description}, creative flat-style logo design, trending on dribbble, featured on behance, portfolio piece, minimal flat design, breathtaking graphic design, 8k, high resolution vector logo, plain background, amazingly beautiful logo design, winner of best logo award", None),
    ("Game Art Icon", "{description}, a concept art icon for league of legends, a digital art logo, illustration, league of legends style icon, inspired by wlop style, 8k, dota 2 style icon, fine details, sharp, very detailed icon, high resolution rpg ability/spell/item icon", None),
    ("Digital Painting Icon", "{description}, app logo icon, digital art pictogram icon, trending on artstation, app icon in the style of atey ghailan, app icon in the style of greg rutkowski, app icon in the style of greg tocchini, app icon in the style of james gilleard, 8k, high resolution, best quality", None),
    ("Concept Art Icon", "{description}, a concept art icon, a digital art logo, illustration, league of legends style concept art logo icon, inspired by wlop style, 8k, fine details, sharp, very detailed, high resolution logo icon", None),
    ("Cute 3D Icon", "{description}, a cute 3D icon of {description}, cartoon 3D icon, very cute shape, stylized octane render, 8k, masterpiece, soooo cute, beautiful cute perfection, beautiful soft lighting, soft colors, centered, high resolution, {description}, soft gradient background", None),
    ("Cute 3D Icon ", "{description}, a set of lovely little 3D icons, cute 3D icons, very cute shapes, stylized octane render, 8k, masterpiece, soooo cute, beautiful cute perfection, beautiful soft lighting, soft colors, centered, high resolution, {description}, cute icon set", None),
    ("Crayon Drawing", "{description}, crayon drawing", None),
    ("Pencil", "black and white pencil drawing, {description}, black and white, breathtaking pencil illustration, highly detailed, 4k, textured paper, pencil texture, sketch", None),
    ("Tattoo Design", "amazing tattoo design, {description}, breathtaking tattoo design, incredible tattoo design", None),
    ("Waifu", "{description}, waifu character portrait, 1girl, very high resolution, semi-realistic anime art. Intricate and impressive anime artwork with stunningly beautiful composition and style. Overall, it's an absolute world-class masterpiece anime artwork. It's an aesthetically pleasing waifu artwork with impeccable attention to detail and impressive composition. It's an aesthetically pleasing character portrait. It's an aesthetically pleasing image. It's an aesthetically pleasing image. It's an aesthetically pleasing image. It's an aesthetically pleasing image.", None),
    ("YuGiOh Art", "yugioh card art for {description}, art in the style of genzoman, in the style of Akina Fujiwara, in the style of rossdraws, yugioh monster, close up, painterly details, breathtaking art, centered, masterpiece, amazing composition,. Overall, it's an absolute world-class masterpiece \"Yu-Gi-Oh!\"-inspired artwork. It's an aesthetically pleasing Yu-Gi-Oh inspired artwork with impeccable attention to detail and impressive composition.", None),
    ("Traditional Japanese", "{description}, in ukiyo-e art style, traditional japanese masterpiece", None),
    ("Nihonga Painting", "japanese nihonga painting about {description}, Nihonga, ancient japanese painting, intricate, detailed", None),
    ("Claymation", "{description}, claymation, incredible claymation style, kubo and the two strings style art, Missing Link 2019 art style, clay texture, clay animation, stop-motion clay", None),
    ("Cartoon", "{description}, cartoon-style art, superb linework, nice colors and composition, bold linework, masterpiece, cute art in the style of Dana Terrace, in the style of Rebecca Sugar, in the style of ry-spirit, amazing and wholesome cartoon-style art, cute art style, (trending on artstation)", None),
    ("Cursed Photo", "cursed photo of {description}, creepy and cursed, absolutely cursed photo, nope nope nope nope, what the actual f, unsettling photo, cursed_thing, cursedimages, no context, cursed image, bad photo, weird photo, very strange, color photo, creepy photo, nightmare fuel", None),
]

def apply_art_style_to_prompt(style_name: str, description: str) -> str:
    """Transforms raw prompt string with the given art style template."""
    template = None
    transform = None
    for name, tmpl, tr in ART_STYLES:
        if name == style_name:
            template = tmpl
            transform = tr
            break
    if template is None:
        return description
    
    if transform:
        description = transform(description)
    
    if "{description}" in template:
        styled_prompt = template.replace("{description}", description)
    else:
        if description:
            styled_prompt = f"{description}, {template}"
        else:
            styled_prompt = template
            
    styled_prompt = re.sub(r",\s*,+", ",", styled_prompt)
    styled_prompt = re.sub(r"^\s*,\s*", "", styled_prompt)
    styled_prompt = re.sub(r",\s*$", "", styled_prompt)
    styled_prompt = re.sub(r"\s+", " ", styled_prompt).strip()
    return styled_prompt

